### ISSUE TITLE
Rapid Reporter window entry field doesn't support copy-paste.

### ISSUE THREAD

**Issue by woodybrood** [Skyscanner/RapidReporterMac#1]
Trying out the app and when I try to copy or paste into the entry field I get a beep from the OS and nothing is inserted.

Steps to Reproduce:

1. Launch a session
2. copy something to the clipboard
3. Click on the entry field
4. CMD+V
5. Beep occurs and pasting is disallowed.

Copy action gets the same noise and nothing is added to the clipboard.

Expected Behavior:
Users should be able to paste plain text. This is helpful in capturing data that doesn't need to be in a rtf note.

**Comment by deefex** [comment]
Thanks for the heads up. Text fields don’t support cut and paste by default in Swift so we had to extend the base class to add it.

**Comment by deefex** [comment]
Fixed
